version: '3.9'

services:
  server:
    # Production (release) mode: minimum set of mounts,
    # all data (e.g. uploads) is stored in volume.
    image: card1nal/cloud_code_server:latest
    ports:
      - "5000:5000"
    volumes:
      - uploads:/uploads
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Tasks:/app/Tasks
    environment:
      - DEBUG_MODE=false
      - WATCH_MODE=false
      - DB_SERVER=mssql;
      - DB_USER=sa
      - DB_PASSWORD=YourStrong!Passw0rd
      - DB_NAME=cloudcode
    depends_on:
      - mssql
      - db-init

  develop:
    # Development mode: debugging is enabled, source files are mounted,
    # so that changes are immediately reflected without rebuilding the container.
    image: card1nal/cloud_code_server:latest
    ports:
      - "5000:5000"
    volumes:
      - uploads:/uploads
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Tasks:/app/Tasks
    environment:
      - DEBUG_MODE=true
      - WATCH_MODE=true
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DB_SERVER=mssql;
      - DB_USER=sa
      - DB_PASSWORD=YourStrong!Passw0rd
      - DB_NAME=cloudcode
    depends_on:
      - mssql
      - db-init
    profiles:
      - develop

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - mssql
    restart: "no"
    volumes:
      - ./Server/SETUP.sql:/tmp/SETUP.sql:ro
    environment: >
      /bin/bash -e -c "
        for i in {1..30}; do
          /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P 'YourStrong!Passw0rd' -Q 'SELECT 1' && break
          sleep 2
        done

        /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P 'YourStrong!Passw0rd' -Q \"
          IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'cloudcode')
          BEGIN
            CREATE DATABASE cloudcode;
          END;
        \"

        /opt/mssql-tools/bin/sqlcmd -S mssql -d cloudcode -U sa -P 'YourStrong!Passw0rd' -i /tmp/SETUP.sql
      "
    networks:
      - default
      
  # Basic configuration for all test services
  test-base: &test-base
    image: card1nal/cloud_code_server:latest
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - uploads:/uploads
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Tasks:/app/Tasks
    environment:
      - APP_DEBUG=true
      - PYTHONPATH=/app
      - DEBUG_MODE=true
    depends_on:
      - server
    profiles:
      - testing
      
  # Running server tests
  tests-server:
    <<: *test-base
    command: ["python", "Tests/run_server_tests.py"]
    
  # Running server unit tests
  tests-server-unit:
    <<: *test-base
    command: ["python", "-m", "unittest", "discover", "-s", "Tests/server/unit"]
    
  # Running server integration tests
  tests-server-integration:
    <<: *test-base
    command: ["python", "-m", "unittest", "discover", "-s", "Tests/server/integration"]
    
  # Running server behave tests
  tests-server-behave:
    <<: *test-base
    command: ["behave", "Tests/server/features"]

volumes:
  uploads:
    name: cloudcode_uploads
    external: true
  mssql-data: