global:
  scrape_interval: 10s 
  evaluation_interval: 10s 

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "flask_server"
    static_configs:
      - targets: ["localhost:5000"]